dist: precise
language: python
sudo: false
env:
  global:
    - PYTHON_VERSION=3.5
    - secure: "ZRCSJe2u1T7LtcKmy0jy8L1IdX4KIgwM79vm8/ZAjq4bfcNDjJu3mBsFy0sPx4A91abfZeG2vgp0D3/sWfrXzRvxcXv983lhvfgc0UL3ZOuCwl8cpNreH75AC+Z2zjohrq9wNmZQNCYd89xmkybzY9tS0d6UAFrh4Dh39FiYtDU="
  matrix:
    - TEST_ADD_STUDIES=False COVER_PACKAGE=qiita_db
    - TEST_ADD_STUDIES=False COVER_PACKAGE=qiita_pet
    - TEST_ADD_STUDIES=True COVER_PACKAGE="qiita_core qiita_ware"
before_install:
  - redis-server --version
  - redis-server --port 7777 &
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.3.31-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Downloading and setting up ascp for EBI testing
  - wget ftp://ftp.microbio.me/pub/qiita/ascp-install-3.5.4.102989-linux-64-qiita.sh -O ascp-install-3.5.4.102989-linux-64-qiita.sh
  - chmod +x ascp-install-3.5.4.102989-linux-64-qiita.sh
  - ./ascp-install-3.5.4.102989-linux-64-qiita.sh
install:
  # install a few of the dependencies that pip would otherwise try to install
  # when intalling scikit-bio
  - travis_retry conda create -q --yes -n qiita python=2.7 pip nose flake8
    pyzmq 'networkx<2.0' pyparsing natsort mock future libgfortran seaborn nltk
    'pandas>=0.18' 'matplotlib>=1.1.0' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1'
  - source activate qiita
  - pip install -U pip
  - pip install sphinx sphinx-bootstrap-theme nose-timer codecov
  - 'echo "backend: Agg" > matplotlibrc'
  - git clone https://github.com/nicolasff/webdis
  - pushd webdis
  - make
  - ./webdis &
  - popd
  - travis_retry pip install . --process-dependency-links
  # loading redbiom with Qiita's test set
  # but first let's make sure redis is empty
  # following https://github.com/biocore/redbiom/blob/master/Makefile
  - export REDBIOM_HOST=http://127.0.0.1:7379
  - curl -s http://127.0.0.1:7379/FLUSHALL > /dev/null
  - redbiom admin scripts-writable
  - redbiom admin create-context --name "qiita-test" --description "qiita-test context"
  - redbiom admin load-sample-metadata --metadata `pwd`/qiita_db/support_files/test_data/templates/1_19700101-000000.txt
  - redbiom admin load-sample-metadata-search --metadata `pwd`/qiita_db/support_files/test_data/templates/1_19700101-000000.txt
  - redbiom admin load-sample-data --table `pwd`/qiita_db/support_files/test_data/processed_data/1_study_1001_closed_reference_otu_table.biom --context qiita-test --tag 4
  - redbiom admin load-sample-data --table `pwd`/qiita_db/support_files/test_data/processed_data/1_study_1001_closed_reference_otu_table-for_redbiom_tests.biom --context qiita-test --tag 5
  - mkdir ~/.qiita_plugins
  - export REDBIOM_HOST=http://127.0.0.1:7379
  - cp $PWD/qiita_core/support_files/BIOM\ type_2.1.4.conf ~/.qiita_plugins/BIOM\ type_2.1.4\ -\ Qiime2.conf
  - touch ~/.bash_profile
  # Install the biom plugin so we can run the analysis tests
  - wget https://data.qiime2.org/distro/core/qiime2-2017.12-py35-linux-conda.yml
  - travis_retry conda env create -q -n qtp-biom --file qiime2-2017.12-py35-linux-conda.yml
  - rm qiime2-2017.12-py35-linux-conda.yml
  - source activate qtp-biom
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  - pip install https://github.com/qiita-spots/qtp-biom/archive/master.zip --process-dependency-links
  - export QIITA_SERVER_CERT=`pwd`/qiita_core/support_files/server.crt
  - source deactivate
  - source activate qiita
before_script:
  - qiita-env make --no-load-ontologies
  - qiita-test-install
script:
  # Some of the tests rely on the plugin system to complete successfuly.
  # Thus, we need a qiita webserver running to be able to execute the tests.
  - qiita pet webserver --no-build-docs start &
  - sleep 5
  - QIITA_PID=$!
  - nosetests $COVER_PACKAGE --with-doctest --with-coverage --with-timer -v --cover-package=$COVER_PACKAGE
  - kill $QIITA_PID
  - if [ ${TEST_ADD_STUDIES} == "True" ]; then test_data_studies/commands.sh ; fi
  - if [ ${TEST_ADD_STUDIES} == "True" ]; then all-qiita-cron-job; fi
  - flake8 qiita_* setup.py scripts/qiita*
  - qiita pet webserver
addons:
  postgresql: "9.3"
services:
  - redis-server
  - postgresql
after_success:
  - if [ ${TEST_ADD_STUDIES} == "False" ]; then codecov ; fi
